name: Build and Release APK

on:
  push:
    branches:
      - main
  workflow_dispatch:

  - name: Create file
    run: cat /home/runner/work/<Project-Name>/<Project-Name>/app/google-services.json | base64

  - name: Putting data
    env:
      DATA: ${{ secrets.GOOGLE_SERVICES_JSON }}
    run: echo $DATA > /home/runner/work/<Project-Name>/<Project-Name>/app/google-services.json

jobs:
  build:
    runs-on: ubuntu-latest
    name: Build and Release
    continue-on-error: true
    steps:
      - uses: actions/checkout@v3
      - name: set up JDK 11
        uses: actions/setup-java@v3
        with:
          distribution: 'adopt'
          java-version: '11'
      - name: Add executable permission to gradlew
        run: chmod +x gradlew
      - name: Clean Project
        run: ./gradlew clean
      - name: Run Tests
        run: ./gradlew test
      - name: Build Project
        run: ./gradlew assemble
      - name: Build Debug APK
        run: bash ./gradlew :app:assembleDebug
      - name: build release
        run: ./gradlew assembleRelease
      - name: Upload APK
        uses: actions/upload-artifact@v3
        with:
          name: apk
          path: app/build/outputs/apk/debug/**.apk